### ISSUE TITLE
Unite the sparse forces around the world

### ISSUE THREAD

**Issue by ManuelSchneid3r** [AlbertExtensions/Ideas#14]
Hi, author here. I'd really like to see us (albert fanboys :D) working together somewhere. I created a community repo. It would be cool if you could move your stuff there. 

https://github.com/albertlauncher/python_community

I just have to figure out how mgmt of communities on github works :D

**Comment by BharatKalluri** [comment]
Hi @ManuelSchneid3r , awesome to hear that this is finally happening. As far as I understand, the plan is to put all the extensions in a single repo and build a package manager around it? or is it just one repo with the world of extensions and one should just clone the repo in the appropriate location and have everything.

Please clarify if I am wrong about your idea, I strongly believe we need to have a frontend for all the extensions so that it encourages people to expand and discover Albert's power.

Really excited about the changes, let me know if I can help you with anything!

**Comment by ManuelSchneid3r** [comment]
Well for now its just the repository where I hope ppl will put useful stuff. When this repo is accepted and used I want to make some sort of in app extension browser/manager which will allow you to download the extensions in this repo.

**Comment by BharatKalluri** [comment]
I think the way to go is to mimic flathub (https://github.com/flathub/flathub/wiki/App-Submission) And create a store out of it. It would be awesome if we had a simple package installer along with Albert(I could help with that, could be a simple python cli tool). It looks python-community is currently empty with a couple of PR's. I will move all these extensions once we have a system in place with a GUI. Thanks for Albert :)
